### PR TITLE
fix(registry/consul):fix can't get service instance in async mode

### LINKED ISSUE #1727: consul服务注册和发现两个问题
问题1：服务A已起来，但其他服务在20秒内无法发现服务A，原因是默认健康检查间隔 20 秒
问题2：服务A启动时去发现其他服务，结果无法找到节点，原因是consul的服务发现底层目前是异步的，需要先同步请求一次

### PR DESCRIPTION
**Pull request by letian0805**
#### Which issue(s) this PR fixes (resolves / be part of):

fixes #1727  problem 2

### CODE REVIEW

File: contrib/registry/consul/registry.go [hunk 1]
```diff
@@ -135,7 +135,7 @@ func (r *Registry) Watch(ctx context.Context, name string) (registry.Watcher, er
 	}
 
 	if !ok {
-		go r.resolve(set)
+		r.resolve(set)
```
Comment (tonybase) [inline contrib/registry/consul/registry.go:138]: If resolve fails the first time, an error should be returned.

Comment (letian0805) [reply contrib/registry/consul/registry.go]: Yes, you are right.

**Review by letian0805 — COMMENTED** [review]
@longXboy @haiyux

**Review by tonybase — APPROVED** [review]
